AWSTemplateFormatVersion: "2010-09-09" 
Description: EC2 instance launch 

Parameters:
  EC2InstanceType:
    Type: String 
    AllowedValues:
      - t2.micro
      - t3.small
    Description: Type of EC2 Instance to deploy

  EC2InstanceName:
    Type: String
    Description: Name to assign to the EC2 Instance

Resources:
  InstanceLaunch:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0ebfd941bbafe70c6
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref HTTPSecurityGroup

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable port 80 and port 443
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
