version = 0.1
[default.deploy.parameters]
stack_name = "project-03-sam-stack"
resolve_s3 = true
s3_prefix = "project-03-sam-stack"
region = "us-east-1"
profile = "September-Admin"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBTableName=\"project-03-from-sam\""
image_repositories = []
