AWSTemplateFormatVersion: "2010-09-09"
Description: Creation for a new table 

Parameters:
  DynamoDBTableName:
    Type: String 
    Description: DynamoDB Table Name 
  ReadingAbility:
    Type: Number 
    Description: Reading capacity for DynamoDb table
    MinValue: 1
    MaxValue: 100
  WritingAbility:
    Type: Number
    Description: Writing capacity for DynamoDB table
    MinValue: 1
    MaxValue: 100

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table 
    Properties:
      TableName: !Ref DynamoDBTableName 
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH 
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadingAbility
        WriteCapacityUnits: !Ref WritingAbility
